name: 'Build on debian/ubuntu in container'

on:
  push:
    branches: [main, gha]

jobs:
  bullseye-container-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["debian:bullseye", "debian:bookworm", "ubuntu:focal", "ubuntu:jammy"]
    container:
      image: ghcr.io/johanvdw/saga-watem-build-${{ matrix.os }}
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: run cmake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        make
        IFS=':' read -r os release <<< '${{ matrix.os }}'
        zip "saga_watem_$release.zip" $(find . -name *.so) -j
    - name: run tests
      run: |
        pytest-3 -vv || true
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Release zip files
        Path: build/*.zip
      
  bullseye-container-build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["debian:bullseye", "debian:bookworm", "ubuntu:focal", "ubuntu:jammy"]
    container:
      image: ghcr.io/johanvdw/saga-watem-build-${{ matrix.os }}
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: build deb packages
      shell: bash
      run: |
        IFS=':' read -r os release <<< '${{ matrix.os }}'
        dch --newversion $(git describe --tags)~$release  "autobuild $(git describe --tags)"
        fakeroot debian/rules binary
        mv ../*.deb .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: debian package
        Path: "*.deb"
